# Only allow cachemgr access from localhost
http_access allow localhost manager
http_access deny manager

# We strongly recommend the following be uncommented to protect innocent
# web applications running on the proxy server who think the only
# one who can access services on "localhost" is a local user
http_access deny to_localhost

# Application logs to syslog, access and store logs have specific files
cache_log       stdio:/var/log/squid/cache.log
access_log      stdio:/var/log/squid/access.log
cache_store_log stdio:/var/log/squid/store.log

# Required by systemd service
pid_filename    /run/squid.pid

# Run as user and group squid
cache_effective_user squid squid

#
# INSERT YOUR OWN RULE(S) HERE TO ALLOW ACCESS FROM YOUR CLIENTS
#
acl vpn_domains dstdomain \
  .discord.com .discordapp.com .discordapp.net .discord.gg .discord.media \
  .youtube.com .ytimg.com .googlevideo.com .youtu.be .ggpht.com \
  .telegram.org .telegram.me .t.me .cdn-telegram.org \
  .githubcopilot.com .github.com .githubusercontent.com \
  .chess.com \
  .7tv.io .7tv.app .betterttv.com .betterttv.net .frankerfacez.com \
  .waterpunk.ru \
  .hollowknight.wiki .wikimg.net \
  .instagram.com .cdninstagram.com \
  .wiki-race.com \
  .matrix.to .element.io .matrix.org .vector.im \
  .speedrun.com \
  .neovim.io \
  .sentry.io .wandb.ai \
  .ivpn.net \
  .haskell.org \
  .vdo.ninja \
  .ngrok.com \
  .momentjs.com

acl telegram_nets dst 149.154.160.0/22 149.154.164.0/22 91.108.4.0/22 91.108.8.0/22 91.108.56.0/22 91.108.64.0/22

tcp_outgoing_mark @IVPN_MARK@ vpn_domains
tcp_outgoing_mark @IVPN_MARK@ telegram_nets
http_upgrade_request_protocols OTHER allow all

http_access allow localhost

# And finally deny all other access to this proxy
http_access deny all

# Squid normally listens to port 3128
http_port @PROXY_PORT@

# Leave coredumps in the first cache dir
coredump_dir /var/cache/squid

cache deny all
