return {
  { "<leader>gst", vim.cmd.Git,                        desc = "[G]it [ST]atus" },
  { "<leader>glg", ":Git log<cr>",                     desc = "[G]it [L]o[G]",               silent = true },
  { "<leader>gcm", ":Git commit<cr>",                  desc = "[G]it [C]o[M]mit",            silent = true },
  { "<leader>gca", ":Git commit --amend<cr>",          desc = "[G]it [C]ommit --[A]mend",    silent = true },
  { "<leader>gcf", ":Git commit --fixup=",             desc = "[G]it [C]ommit --[F]ixup",    silent = true },
  { "<leader>gsw", ":Git switch ",                     desc = "[G]it [SW]itch" },
  { "<leader>gph", ":Git push<cr>",                    desc = "[G]it [P]us[H]",              silent = true },
  { "<leader>gpf", ":Git push --force-with-lease<cr>", desc = "[G]it [P]ush by [F]orce",     silent = true },
  { "<leader>gpl", ":Git pull<cr>",                    desc = "[G]it [P]ul[L]",              silent = true },
  { "<leader>gsh", ":Git stash --all<cr>",             desc = "[G]it [S]tas[H]",             silent = true },
  { "<leader>gsp", ":Git stash pop<cr>",               desc = "[G]it [S]tash [P]op",         silent = true },
  { "<leader>gbl", ":Git blame -w -C -C -C<cr>",       desc = "[G]it [BL]ame",               silent = true },
  { "<leader>grb", ":Git rebase ",                     desc = "[G]it [R]e[B]ase" },
  { "<leader>gri", ":Git rebase --interactive ",       desc = "[G]it [R]ebase [I]nteractive" },
  { "<leader>grc", ":Git rebase --continue<cr>",       desc = "[G]it [R]ebase [C]ontinue",   silent = true },
  { "<leader>grs", ":Git reset ",                      desc = "[G]it [R]e[S]et" },
  { "<leader>grl", ":Git reflog<cr>",                  desc = "[G]it [R]ef[L]og" },
  { "<leader>gmg", ":Git merge ",                      desc = "[G]it [M]er[G]e" },
  { "<leader>gfh", ":Git fetch<cr>",                   desc = "[G]it [F]etc[H]",             silent = true },
}
