vim.keymap.set("n", "<leader>gst", vim.cmd.Git)
vim.keymap.set("n", "<leader>glg", ":Git log<cr>")
vim.keymap.set("n", "<leader>gcm", ":Git commit<cr>")
vim.keymap.set("n", "<leader>gca", ":Git commit --amend<cr>")
vim.keymap.set("n", "<leader>gsw", ":Git switch ")
vim.keymap.set("n", "<leader>gph", ":Git push<cr>")
vim.keymap.set("n", "<leader>gpl", ":Git pull<cr>")
vim.keymap.set("n", "<leader>gsh", ":Git stash<cr>")
vim.keymap.set("n", "<leader>gsp", ":Git stash pop<cr>")
vim.keymap.set("n", "<leader>gbl", ":Git blame<cr>")
vim.keymap.set("n", "<leader>grb", ":Git rebase ")
vim.keymap.set("n", "<leader>gmg", ":Git merge ")
vim.keymap.set("n", "<leader>gfh", ":Git fetch<cr>")
