local telescope = require("telescope.builtin")

vim.keymap.set("n", "<leader>sf", telescope.find_files, { desc = "[S]earch for [F]iles" })
vim.keymap.set("n", "<leader>sg", telescope.live_grep, { desc = "[S]earch via [G]rep" })
vim.keymap.set("n", "<leader>sb", telescope.buffers, { desc = "[S]earch for [B]uffers" })
vim.keymap.set("n", "<leader>sd", telescope.lsp_document_symbols, { desc = "[S]earch for [D]ocument LSP symbols" })
vim.keymap.set("n", "<leader>sp", telescope.lsp_workspace_symbols, { desc = "[S]earch for [P]roject LSP symbols" })
vim.keymap.set("n", "<leader>se", telescope.diagnostics, { desc = "[S]earch for [E]rrors" })
vim.keymap.set("n", "<leader>sm", telescope.marks, { desc = "[S]earch for [M]arks" })
vim.keymap.set("n", "<leader>sk", telescope.keymaps, { desc = "[S]earch for [K]eymaps" })
vim.keymap.set("n", "<leader>sh", telescope.help_tags, { desc = "[S]earch for [H]elp tags" })
