local to = function(x) return require('nvim-treesitter-textobjects.' .. x) end

return {
  lazy = {
    { ';',           function() return to('repeatable_move').repeat_last_move() end,                            mode = { 'n', 'x', 'o', } },
    { ',',           function() return to('repeatable_move').repeat_last_move_opposite() end,                   mode = { 'n', 'x', 'o', } },
    { 'f',           function() return to('repeatable_move').builtin_f_expr() end,                              mode = { 'n', 'x', 'o', }, expr = true },
    { 'F',           function() return to('repeatable_move').builtin_F_expr() end,                              mode = { 'n', 'x', 'o', }, expr = true },
    { 't',           function() return to('repeatable_move').builtin_t_expr() end,                              mode = { 'n', 'x', 'o', }, expr = true },
    { 'T',           function() return to('repeatable_move').builtin_T_expr() end,                              mode = { 'n', 'x', 'o', }, expr = true },
    { ']b',          function() return to('move').goto_next_start('block.outer', 'textobjects') end,            mode = { 'n', 'x', 'o', }, desc = 'Next [B]lock start' },
    { ']@',          function() return to('move').goto_next_start('call.outer', 'textobjects') end,             mode = { 'n', 'x', 'o', }, desc = 'Next (@)call' },
    { ']c',          function() return to('move').goto_next_start('class.outer', 'textobjects') end,            mode = { 'n', 'x', 'o', }, desc = 'Next [C]lass start' },
    { ']/',          function() return to('move').goto_next_start('comment.outer', 'textobjects') end,          mode = { 'n', 'x', 'o', }, desc = 'Next comment(//)' },
    { ']i',          function() return to('move').goto_next_start('conditional.outer', 'textobjects') end,      mode = { 'n', 'x', 'o', }, desc = 'Next [I]f start' },
    { ']f',          function() return to('move').goto_next_start('function.outer', 'textobjects') end,         mode = { 'n', 'x', 'o', }, desc = 'Next [F]unction start' },
    { ']l',          function() return to('move').goto_next_start('loop.outer', 'textobjects') end,             mode = { 'n', 'x', 'o', }, desc = 'Next [L]oop start' },
    { ']n',          function() return to('move').goto_next_start('number.inner', 'textobjects') end,           mode = { 'n', 'x', 'o', }, desc = 'Next [N]umber start' },
    { ']a',          function() return to('move').goto_next_start('parameter.inner', 'textobjects') end,        mode = { 'n', 'x', 'o', }, desc = 'Next [P]arameter start' },
    { ']e',          function() return to('move').goto_next_start('regex.inner', 'textobjects') end,            mode = { 'n', 'x', 'o', }, desc = 'Next r[E]gex start' },
    { ']r',          function() return to('move').goto_next_start('return.outer', 'textobjects') end,           mode = { 'n', 'x', 'o', }, desc = 'Next [R]eturn start' },
    { ']s',          function() return to('move').goto_next_start('statement.outer', 'textobjects') end,        mode = { 'n', 'x', 'o', }, desc = 'Next [S]tatement start' },
    { ']B',          function() return to('move').goto_next_end('block.outer', 'textobjects') end,              mode = { 'n', 'x', 'o', }, desc = 'Next [B]lock end' },
    { ']C',          function() return to('move').goto_next_end('class.outer', 'textobjects') end,              mode = { 'n', 'x', 'o', }, desc = 'Next [C]lass end' },
    { ']I',          function() return to('move').goto_next_end('conditional.outer', 'textobjects') end,        mode = { 'n', 'x', 'o', }, desc = 'Next [I]f end' },
    { ']F',          function() return to('move').goto_next_end('function.outer', 'textobjects') end,           mode = { 'n', 'x', 'o', }, desc = 'Next [F]unction end' },
    { ']L',          function() return to('move').goto_next_end('loop.outer', 'textobjects') end,               mode = { 'n', 'x', 'o', }, desc = 'Next [L]oop end' },
    { ']N',          function() return to('move').goto_next_end('number.inner', 'textobjects') end,             mode = { 'n', 'x', 'o', }, desc = 'Next [N]umber end' },
    { ']A',          function() return to('move').goto_next_end('parameter.inner', 'textobjects') end,          mode = { 'n', 'x', 'o', }, desc = 'Next [P]arameter end' },
    { ']E',          function() return to('move').goto_next_end('regex.inner', 'textobjects') end,              mode = { 'n', 'x', 'o', }, desc = 'Next r[E]gex end' },
    { ']R',          function() return to('move').goto_next_end('return.outer', 'textobjects') end,             mode = { 'n', 'x', 'o', }, desc = 'Next [R]eturn end' },
    { ']S',          function() return to('move').goto_next_end('statement.outer', 'textobjects') end,          mode = { 'n', 'x', 'o', }, desc = 'Next [S]tatement end' },
    { '[b',          function() return to('move').goto_previous_start('block.outer', 'textobjects') end,        mode = { 'n', 'x', 'o', }, desc = 'Previous [B]lock start' },
    { '[@',          function() return to('move').goto_previous_start('call.outer', 'textobjects') end,         mode = { 'n', 'x', 'o', }, desc = 'Previous (@)call' },
    { '[c',          function() return to('move').goto_previous_start('class.outer', 'textobjects') end,        mode = { 'n', 'x', 'o', }, desc = 'Previous [C]lass start' },
    { '[/',          function() return to('move').goto_previous_start('comment.outer', 'textobjects') end,      mode = { 'n', 'x', 'o', }, desc = 'Previous comment(//)' },
    { '[i',          function() return to('move').goto_previous_start('conditional.outer', 'textobjects') end,  mode = { 'n', 'x', 'o', }, desc = 'Previous [I]f start' },
    { '[f',          function() return to('move').goto_previous_start('function.outer', 'textobjects') end,     mode = { 'n', 'x', 'o', }, desc = 'Previous [F]unction start' },
    { '[l',          function() return to('move').goto_previous_start('loop.outer', 'textobjects') end,         mode = { 'n', 'x', 'o', }, desc = 'Previous [L]oop start' },
    { '[n',          function() return to('move').goto_previous_start('number.inner', 'textobjects') end,       mode = { 'n', 'x', 'o', }, desc = 'Previous [N]umber start' },
    { '[a',          function() return to('move').goto_previous_start('parameter.inner', 'textobjects') end,    mode = { 'n', 'x', 'o', }, desc = 'Previous [P]arameter start' },
    { '[e',          function() return to('move').goto_previous_start('regex.inner', 'textobjects') end,        mode = { 'n', 'x', 'o', }, desc = 'Previous r[E]gex start' },
    { '[r',          function() return to('move').goto_previous_start('return.outer', 'textobjects') end,       mode = { 'n', 'x', 'o', }, desc = 'Previous [R]eturn start' },
    { '[s',          function() return to('move').goto_previous_start('statement.outer', 'textobjects') end,    mode = { 'n', 'x', 'o', }, desc = 'Previous [S]tatement start' },
    { '[B',          function() return to('move').goto_previous_end('block.outer', 'textobjects') end,          mode = { 'n', 'x', 'o', }, desc = 'Previous [B]lock end' },
    { '[C',          function() return to('move').goto_previous_end('class.outer', 'textobjects') end,          mode = { 'n', 'x', 'o', }, desc = 'Previous [C]lass end' },
    { '[I',          function() return to('move').goto_previous_end('conditional.outer', 'textobjects') end,    mode = { 'n', 'x', 'o', }, desc = 'Previous [I]f end' },
    { '[F',          function() return to('move').goto_previous_end('function.outer', 'textobjects') end,       mode = { 'n', 'x', 'o', }, desc = 'Previous [F]unction end' },
    { '[L',          function() return to('move').goto_previous_end('loop.outer', 'textobjects') end,           mode = { 'n', 'x', 'o', }, desc = 'Previous [L]oop end' },
    { '[N',          function() return to('move').goto_previous_end('number.inner', 'textobjects') end,         mode = { 'n', 'x', 'o', }, desc = 'Previous [N]umber end' },
    { '[A',          function() return to('move').goto_previous_end('parameter.inner', 'textobjects') end,      mode = { 'n', 'x', 'o', }, desc = 'Previous [P]arameter end' },
    { '[E',          function() return to('move').goto_previous_end('regex.inner', 'textobjects') end,          mode = { 'n', 'x', 'o', }, desc = 'Previous r[E]gex end' },
    { '[R',          function() return to('move').goto_previous_end('return.outer', 'textobjects') end,         mode = { 'n', 'x', 'o', }, desc = 'Previous [R]eturn end' },
    { '[S',          function() return to('move').goto_previous_end('statement.outer', 'textobjects') end,      mode = { 'n', 'x', 'o', }, desc = 'Previous [S]tatement end' },
    { 'i=',          function() return to('select').select_textobject('@assignment.inner', 'textobjects') end,  mode = { 'x', 'o', } },
    { 'a=',          function() return to('select').select_textobject('@assignment.outer', 'textobjects') end,  mode = { 'x', 'o', } },
    { '=h',          function() return to('select').select_textobject('@assignment.lhs', 'textobjects') end,    mode = { 'x', 'o', } },
    { '=l',          function() return to('select').select_textobject('@assignment.rhs', 'textobjects') end,    mode = { 'x', 'o', } },
    { 'ib',          function() return to('select').select_textobject('@block.inner', 'textobjects') end,       mode = { 'x', 'o', } },
    { 'ab',          function() return to('select').select_textobject('@block.outer', 'textobjects') end,       mode = { 'x', 'o', } },
    { 'i@',          function() return to('select').select_textobject('@call.inner', 'textobjects') end,        mode = { 'x', 'o', } },
    { 'a@',          function() return to('select').select_textobject('@call.outer', 'textobjects') end,        mode = { 'x', 'o', } },
    { 'ic',          function() return to('select').select_textobject('@class.inner', 'textobjects') end,       mode = { 'x', 'o', } },
    { 'ac',          function() return to('select').select_textobject('@class.outer', 'textobjects') end,       mode = { 'x', 'o', } },
    { 'i/',          function() return to('select').select_textobject('@comment.inner', 'textobjects') end,     mode = { 'x', 'o', } },
    { 'a/',          function() return to('select').select_textobject('@comment.outer', 'textobjects') end,     mode = { 'x', 'o', } },
    { 'ii',          function() return to('select').select_textobject('@conditional.inner', 'textobjects') end, mode = { 'x', 'o', } },
    { 'ai',          function() return to('select').select_textobject('@conditional.outer', 'textobjects') end, mode = { 'x', 'o', } },
    { 'if',          function() return to('select').select_textobject('@function.inner', 'textobjects') end,    mode = { 'x', 'o', } },
    { 'af',          function() return to('select').select_textobject('@function.outer', 'textobjects') end,    mode = { 'x', 'o', } },
    { 'il',          function() return to('select').select_textobject('@loop.inner', 'textobjects') end,        mode = { 'x', 'o', } },
    { 'al',          function() return to('select').select_textobject('@loop.outer', 'textobjects') end,        mode = { 'x', 'o', } },
    { 'ia',          function() return to('select').select_textobject('@parameter.inner', 'textobjects') end,   mode = { 'x', 'o', } },
    { 'aa',          function() return to('select').select_textobject('@parameter.outer', 'textobjects') end,   mode = { 'x', 'o', } },
    { 'ie',          function() return to('select').select_textobject('@regex.inner', 'textobjects') end,       mode = { 'x', 'o', } },
    { 'ae',          function() return to('select').select_textobject('@regex.outer', 'textobjects') end,       mode = { 'x', 'o', } },
    { 'ir',          function() return to('select').select_textobject('@return.inner', 'textobjects') end,      mode = { 'x', 'o', } },
    { 'ar',          function() return to('select').select_textobject('@return.outer', 'textobjects') end,      mode = { 'x', 'o', } },
    { 'is',          function() return to('select').select_textobject('@scope.inner', 'textobjects') end,       mode = { 'x', 'o', } },
    { 'as',          function() return to('select').select_textobject('@statement.outer', 'textobjects') end,   mode = { 'x', 'o', } },
    { '<leader>mnb', function() return to('swap').swap_next('@block.inner') end,                                mode = 'n' },
    { '<leader>mnc', function() return to('swap').swap_next('@class.outer') end,                                mode = 'n' },
    { '<leader>mni', function() return to('swap').swap_next('@conditional.inner') end,                          mode = 'n' },
    { '<leader>mnf', function() return to('swap').swap_next('@function.outer') end,                             mode = 'n' },
    { '<leader>mnn', function() return to('swap').swap_next('@number.outer') end,                               mode = 'n' },
    { '<leader>mna', function() return to('swap').swap_next('@parameter.inner') end,                            mode = 'n' },
    { '<leader>mne', function() return to('swap').swap_next('@regex.inner') end,                                mode = 'n' },
    { '<leader>mnr', function() return to('swap').swap_next('@return.inner') end,                               mode = 'n' },
    { '<leader>mns', function() return to('swap').swap_next('@statement.outer') end,                            mode = 'n' },
    { '<leader>mpb', function() return to('swap').swap_previous('@block.inner') end,                            mode = 'n' },
    { '<leader>mpc', function() return to('swap').swap_previous('@class.outer') end,                            mode = 'n' },
    { '<leader>mpi', function() return to('swap').swap_previous('@conditional.inner') end,                      mode = 'n' },
    { '<leader>mpf', function() return to('swap').swap_previous('@function.outer') end,                         mode = 'n' },
    { '<leader>mpa', function() return to('swap').swap_previous('@parameter.inner') end,                        mode = 'n' },
    { '<leader>mpe', function() return to('swap').swap_previous('@regex.inner') end,                            mode = 'n' },
    { '<leader>mpr', function() return to('swap').swap_previous('@return.inner') end,                           mode = 'n' },
    { '<leader>mps', function() return to('swap').swap_previous('@statement.outer') end,                        mode = 'n' },
  },
}
