require('which-key').register {
  ['<leader>g'] = { name = '[G]it', _ = 'which_key_ignore' },
  ['<leader>s'] = { name = '[S]earch', _ = 'which_key_ignore' },
  ['<leader>t'] = { name = '[T]ab/[T]erm', _ = 'which_key_ignore' },
  ['<leader>d'] = { name = '[D]ap', _ = 'which_key_ignore' },
  ['<leader>c'] = { name = '[C]omment', _ = 'which_key_ignore' },
  ['<leader>v'] = { name = '[V]isual selection', _ = 'which_key_ignore' },
  ['<leader>m'] = { name = '[M]ove', _ = 'which_key_ignore' },
  ['<leader>mn'] = { name = '[M]ove to [Next]', _ = 'which_key_ignore' },
  ['<leader>mp'] = { name = '[M]ove to [Previous]', _ = 'which_key_ignore' },
  ['<leader>f'] = { name = '[F]ile', _ = 'which_key_ignore' },
  ['<leader>de'] = { name = '[D]ile [E]xceptions', _ = 'which_key_ignore' },
  ['<leader>ds'] = { name = '[D]ile [S]tep', _ = 'which_key_ignore' },
  ['<leader>ga'] = { name = '[G]it [A]dd', _ = 'which_key_ignore' },
  ['<leader>gb'] = { name = '[G]it [B]lame', _ = 'which_key_ignore' },
  ['<leader>gc'] = { name = '[G]it [C]ommit', _ = 'which_key_ignore' },
  ['<leader>gd'] = { name = '[G]it [D]iff', _ = 'which_key_ignore' },
  ['<leader>gf'] = { name = '[G]it [F]etch', _ = 'which_key_ignore' },
  ['<leader>gl'] = { name = '[G]it [L]ine blame', _ = 'which_key_ignore' },
  ['<leader>gm'] = { name = '[G]it [M]erge', _ = 'which_key_ignore' },
  ['<leader>gp'] = { name = '[G]it [P]ush/[P]ull', _ = 'which_key_ignore' },
  ['<leader>gr'] = { name = '[G]it [R]eset/[R]ebase', _ = 'which_key_ignore' },
  ['<leader>gs'] = { name = '[G]it [S]tash/[S]tatus/[S]witch', _ = 'which_key_ignore' },
}
