require('which-key').add {
  { '<leader>c', desc = '[C]loak' },
  { '<leader>d', desc = '[D]ap' },
  { '<leader>de', desc = '[D]ap [E]xceptions' },
  { '<leader>ds', desc = '[D]ap [S]tep' },
  { '<leader>f', desc = '[F]ile' },
  { '<leader>g', desc = '[G]it' },
  { '<leader>ga', desc = '[G]it [A]dd' },
  { '<leader>gb', desc = '[G]it [B]lame' },
  { '<leader>gd', desc = '[G]it [D]iff' },
  { '<leader>gf', desc = '[G]it [F]etch' },
  { '<leader>gl', desc = '[G]it [L]ine blame' },
  { '<leader>gp', desc = '[G]it [P]ush' },
  { '<leader>gr', desc = '[G]it [R]eset/[R]ebase' },
  { '<leader>gs', desc = '[G]it [S]tatus' },
  { '<leader>m', desc = '[M]ove' },
  { '<leader>mn', desc = '[M]ove to [Next]' },
  { '<leader>mp', desc = '[M]ove to [Previous]' },
  { '<leader>o', desc = 'N[o]ice' },
  { '<leader>s', desc = '[S]earch' },
  { '<leader>t', desc = '[T]ab/[T]erm' },
  { '<leader>v', desc = '[V]isual selection' },
}
