#!/usr/bin/env bash

list_all()
{
    swaymsg -t get_outputs | jq -r '.[] | .name'
}

list()
{
    list_all | grep 'HEADLESS'
}

create()
{
    swaymsg create_output
    list
}

remove()
{
    swaymsg output "$(list | fzf-tmux -p)" unplug
}

show()
{
    DP=$(list_all | fzf-tmux -p)
    wl-mirror "$DP" >/dev/null 2>&1 &
    disown
}

move()
{
    if [[ -z "$1" ]]; then
        DP="$(list_all | fzf-tmux -p)"
    else 
        DP="$(list_all | fzf --filter "$1" | head -n 1)"
    fi
    swaymsg move workspace to "$DP"
}

main()
{
    case $1 in
        c|create) create; exit 0;;
        r|remove) remove; exit 0;;
        l|list) list; exit 0;;
        s|show) show; exit 0;;
        m|move) shift 1; move $@; exit 0;;
        exit) exit 0;;
    esac
    exit 1
}

(main $@) || main $(echo -e "create\nremove\nlist\nexit\nshow\nmove" | fzf-tmux -p)
