#!/usr/bin/env bash

pick()
{
    if [[ -z "$1" ]]; then
        echo "$(list_all | fzf-tmux -p)"
    else
        echo "$(list_all | fzf --filter "$1" | head -n 1)"
    fi
}

list_all()
{
    swaymsg -t get_outputs | jq -r '.[] | .name'
}

list()
{
    list_all | grep 'HEADLESS'
}

create()
{
    swaymsg create_output
    list
}

remove()
{
    swaymsg output "$(list | fzf-tmux -p)" unplug
}

show()
{
    DP="$(pick $@)"
    wl-mirror "$DP" >/dev/null 2>&1 &
    disown
}

move()
{
    DP="$(pick $@)"
    swaymsg move workspace to "$DP"
}

main()
{
    CMD=$1
    shift 1
    case $CMD in
        c|create) create; exit 0;;
        r|remove) remove; exit 0;;
        l|list) list; exit 0;;
        s|show) show $@; exit 0;;
        m|move) move $@; exit 0;;
        exit) exit 0;;
    esac
    exit 1
}

(main $@) || main $(echo -e "create\nremove\nlist\nexit\nshow\nmove" | fzf-tmux -p)
